/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vite_base64_Base64 */

#ifndef _Included_vite_base64_Base64
#define _Included_vite_base64_Base64
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vite_base64_Base64
 * Method:    encodeByByte
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_vite_base64_Base64_encodeByByte
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     vite_base64_Base64
 * Method:    encodeByByte2String
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_vite_base64_Base64_encodeByByte2String
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     vite_base64_Base64
 * Method:    encodeByString
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_vite_base64_Base64_encodeByString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     vite_base64_Base64
 * Method:    encodeByString2String
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_vite_base64_Base64_encodeByString2String
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
